docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - 'Theory and Usage': usage.md
    - 'Refining ACLs': refining.md
    - Reference:
      - 'Ownership Assertions': ownership.md
      - 'Expression Assertions': expression.md
      - 'Advanced Usage': advanced.md
site_name: zend-permissions-acl
site_description: 'Create, manage, and query access control lists.'
repo_url: 'https://github.com/zendframework/zend-permissions-acl'
